name: vehicle_motion_forecasting
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.6
  - jupyter
  - cython
  - numpy=1.14.0
  - numba
  - matplotlib=2.1.2
  - pytorch=0.4.0
  - scipy=1.0.0
  - seaborn==0.9.0
  - tqdm=4.19.4
  - pip
  - pip:
    - visdom==0.1.8.3
